"""The commands that build from a live schema: discover, subset, schema,
synthesize and clear.
"""
from __future__ import annotations

import argparse
import datetime
from typing import Dict, List, Sequence, Tuple

from ..database import Database
from ..database.dialects import catalogTable, quoteIdentifier, quoteTableName
from ..log import Log
from ..log.scrubbing import describeError
from .common import (EXIT_JOBS_DID_NOT_SUCCEED, EXIT_SUCCESS, UsageError, _discoveryRules, _loadDatabases, _loadDataJobs, _memoryBackend,
                     _requireAlias, _selectJobs, _writeOutput)


def _generatedHeading(command: str, source: str, target: str) -> List[str]:

    return [
        'Generated by `bauta {}` on {} from {}, loading into {}.'.format(command, datetime.date.today().isoformat(), source, target),
        '',
        'A proposal, not a policy. Review every column before running this -- the',
        'comment on each says what the suggestion was based on -- and set',
        'MASKING_KEY in the environment. Sampled values were read only to classify',
        'columns; none of them appear in this file.',
        '',
        ]


def _nextSteps(source: str, target: str, tables: Sequence[str], related: bool = False) -> List[str]:
    """How to create the tables the generated jobs load, and how to refresh them."""

    tableArguments = ' '.join('--table {}'.format(table) for table in tables)
    if source == target:
        return [
            'Masking in place loads through <table>_masked_stage. Create the stage tables with:',
            '  bauta schema --database {0} --target {0} {1} --stage-suffix _masked_stage --apply'.format(source, tableArguments),
            '',
            ]

    return [
        'Create any target tables that do not exist yet with:',
        '  bauta schema --database {} --target {} {}{} --apply'.format(source, target, tableArguments, ' --related' if related else ''),
        'To refresh the copy later, empty it first, then run every job:',
        '  bauta clear --config <this directory> --yes && bauta run --config <this directory> --force',
        '',
        ]


def _requireTableSelection(arguments: argparse.Namespace) -> None:
    """Either the tables are named, or every one of them is asked for."""

    if arguments.all_tables and arguments.table:
        raise UsageError('--all-tables and --table name two different sets of tables; give one or the other')
    if not arguments.all_tables and not arguments.table:
        raise UsageError('name the tables with --table, repeated, or take every one with --all-tables')


def _commandDiscover(arguments: argparse.Namespace, log: Log) -> int:
    """Proposes a masking policy for each table from its schema and a sample,
    writing nothing to any database.
    """

    from ..generate.discovery import JobDraft, proposeTable, renderJobs

    _requireTableSelection(arguments)
    databaseConfiguration = _loadDatabases(arguments)
    rules = _discoveryRules(arguments)
    target = arguments.target or arguments.database
    _requireAlias(databaseConfiguration, arguments.database)
    _requireAlias(databaseConfiguration, target)

    drafts = []
    with Database(connectionSettings=databaseConfiguration[arguments.database]) as database:
        try:
            foreignKeys = database.getForeignKeys()
        except NotImplementedError:
            foreignKeys = []
        # Named as the catalog holds them, so a table written in quotes -- the
        # only way to name a reserved word -- matches its own foreign keys, and
        # gives a job and a key domain the same name a bare one would.
        requestedTables = database.listTables(schema=arguments.schema) if arguments.all_tables else arguments.table
        if not requestedTables:
            raise UsageError('{} holds no tables{}'.format(
                arguments.database, ' in schema {}'.format(arguments.schema) if arguments.schema else ''))
        tables = [catalogTable(database.type, table) for table in requestedTables]
        requested = {table.upper(): table for table in tables}
        for table in tables:
            log.logging.info('Sampling up to {} row(s) of {}'.format(arguments.sample, table))
            proposal = proposeTable(database, table, sampleSize=arguments.sample, foreignKeys=foreignKeys, rules=rules,
                                    maskKeys=arguments.mask_keys)
            # Parents first, so a target that enforces foreign keys accepts the load.
            parents = sorted({requested[foreignKey.referencedTable.upper()] for foreignKey in foreignKeys
                              if foreignKey.table.upper() == table.upper() and foreignKey.referencedTable.upper() in requested
                              and foreignKey.referencedTable.upper() != table.upper()})
            drafts.append(JobDraft(table=table, sourceQuery='SELECT * FROM {}'.format(database.statementName(table)),
                                   predecessors=parents, proposal=proposal))

    heading = _generatedHeading('discover', arguments.database, target) + _nextSteps(arguments.database, target, requestedTables)
    _writeOutput(renderJobs(drafts, arguments.database, target, heading, keyVariable=arguments.key_variable,
                            chunkSize=arguments.chunk_size, targetType=databaseConfiguration[target].type), arguments.output)

    return EXIT_SUCCESS


def _commandSubset(arguments: argparse.Namespace, log: Log) -> int:
    """Generates one data job per table for a referentially complete subset,
    loading parents before children, with masking proposals if --mask is set.
    """

    from ..generate.discovery import JobDraft, proposeTable, renderJobs
    from ..generate.subset import SubsetError, planSubset

    databaseConfiguration = _loadDatabases(arguments)
    rules = _discoveryRules(arguments)
    _requireAlias(databaseConfiguration, arguments.database)
    _requireAlias(databaseConfiguration, arguments.target)

    if arguments.target == arguments.database:
        raise UsageError('--target must differ from --database: a subset is loaded into another database, not over its source')

    with Database(connectionSettings=databaseConfiguration[arguments.database]) as database:
        foreignKeys = database.getForeignKeys()

        try:
            plan = planSubset(foreignKeys, root=arguments.root, where=arguments.where, followChildren=not arguments.no_children,
                              ignore=arguments.ignore_foreign_key or [], materialize=database.dialect.supportsMaterializedSelections(),
                              quote=lambda name: quoteIdentifier(database.type, name),
                              quoteTable=lambda name: quoteTableName(database.type, name))
        except SubsetError as error:
            raise UsageError(str(error)) from error

        log.logging.info('Subset covers {} table(s): {}'.format(len(plan.tables), ', '.join(plan.tables)))
        for foreignKey in plan.ignored:
            log.logging.warning('Ignoring foreign key {}.{} -> {}; rows may reference ones outside the subset'.format(
                foreignKey.table, ','.join(foreignKey.columns), foreignKey.referencedTable))

        drafts = []
        for table in plan.tables:
            proposal = proposeTable(database, table, sampleSize=arguments.sample, foreignKeys=foreignKeys, rules=rules,
                                    maskKeys=arguments.mask_keys) if arguments.mask else None
            drafts.append(JobDraft(table=table, sourceQuery=plan.queries[table], predecessors=plan.parents[table], proposal=proposal))

    heading = _generatedHeading('subset', arguments.database, arguments.target) + [
        'Rooted at {} where {}.'.format(arguments.root, arguments.where),
        'Jobs load parents before children, so the target can keep its foreign keys.',
        '',
        ] + _nextSteps(arguments.database, arguments.target, [arguments.root], related=True)
    _writeOutput(renderJobs(drafts, arguments.database, arguments.target, heading, keyVariable=arguments.key_variable,
                            chunkSize=arguments.chunk_size, targetType=databaseConfiguration[arguments.target].type), arguments.output)

    return EXIT_SUCCESS


def _commandSchema(arguments: argparse.Namespace, log: Log) -> int:
    """Generates CREATE TABLE statements for the target, or applies them.

    --apply skips tables the target already has, so it's safe to re-run, and
    never alters or drops anything.
    """

    from ..generate.schema import SchemaError, createStatements, readTable, renderScript
    from ..generate.subset import relatedTables

    databaseConfiguration = _loadDatabases(arguments)
    _requireAlias(databaseConfiguration, arguments.database)
    _requireAlias(databaseConfiguration, arguments.target)

    sourceSettings = databaseConfiguration[arguments.database]
    targetSettings = databaseConfiguration[arguments.target]
    stagesOnly = arguments.database == arguments.target

    if stagesOnly and not arguments.stage_suffix:
        raise UsageError('--target is the source database, so its tables already exist; pass --stage-suffix to create stage tables for them')

    with Database(connectionSettings=sourceSettings) as source:
        foreignKeys = source.getForeignKeys()
        tables = relatedTables(foreignKeys, arguments.table, followChildren=not arguments.no_children) if arguments.related else arguments.table
        try:
            definitions = [readTable(source, table, foreignKeys) for table in tables]
            statements = createStatements(sourceSettings.type, targetSettings.type, definitions, includeForeignKeys=not arguments.no_foreign_keys,
                                          stageSuffix=arguments.stage_suffix, stagesOnly=stagesOnly)
        except SchemaError as error:
            raise UsageError(str(error)) from error

    if not arguments.apply:
        heading = [
            'Generated by `bauta schema` on {} from {} ({}), for {} ({}).'.format(
                datetime.date.today().isoformat(), arguments.database, sourceSettings.type.value, arguments.target, targetSettings.type.value),
            'Columns, nullability, primary keys and foreign keys only: no indexes, defaults or constraints beyond those.',
            'Review the commented type choices before applying.',
            ]
        _writeOutput(renderScript(statements, heading), arguments.output)
        return EXIT_SUCCESS

    created = skipped = 0
    with Database(connectionSettings=targetSettings) as target:
        for statement in statements:
            if target.tableExists(statement.table):
                log.logging.info('{}: already exists, left as it is'.format(statement.table))
                skipped += 1
                continue
            for note in statement.notes:
                log.logging.warning('{}: {}'.format(statement.table, note))
            try:
                target.alter(statement.sql)
            except Exception as error:
                raise UsageError('could not create {} ({} created before it): {}'.format(
                    statement.table, created, describeError(error))) from error
            log.logging.info('{}: created'.format(statement.table))
            created += 1

    print('schema applied to {}: {} table(s) created, {} already existed'.format(arguments.target, created, skipped))

    return EXIT_SUCCESS


def _parseTableRows(entries: Sequence[str], default: int) -> List[Tuple[str, int]]:
    """`--table orders:500` entries, with `--rows` for any without a count."""

    parsed = []
    for entry in entries:
        table, separator, count = entry.rpartition(':')
        if not separator:
            parsed.append((entry, default))
            continue
        if not table or not count.isdigit() or int(count) < 1:
            raise UsageError('--table takes TABLE or TABLE:ROWS with a positive count, got {!r}'.format(entry))
        parsed.append((table, int(count)))

    return parsed


def _commandSynthesize(arguments: argparse.Namespace, log: Log) -> int:
    """Fills existing tables with generated rows, parents first.

    Writes only with --yes, like `clear`. --dry-run shows what each column
    would get and a few generated rows, which are safe to print.
    """

    from ..generate.schema import SchemaError, orderParentsFirst
    from ..generate.synthesize import SynthesisError, planTable, synthesizeTable

    databaseConfiguration = _loadDatabases(arguments)
    rules = _discoveryRules(arguments)
    _requireAlias(databaseConfiguration, arguments.database)
    requested = dict(_parseTableRows(arguments.table, arguments.rows))

    if not arguments.dry_run and not arguments.yes:
        raise UsageError('synthesize inserts generated rows into {}; pass --yes to do it, or --dry-run to see the plan'.format(
            ', '.join(requested)))

    with Database(connectionSettings=databaseConfiguration[arguments.database]) as database:
        foreignKeys = database.getForeignKeys()
        try:
            order = orderParentsFirst(requested, foreignKeys)
        except SchemaError as error:
            raise UsageError(str(error)) from error

        for table in order:
            rows = requested[table]
            try:
                if arguments.dry_run:
                    columns, makeRow, plans, available = planTable(database, table, rows, seed=arguments.seed, foreignKeys=foreignKeys, rules=rules)
                    print('{}: {} row(s){}'.format(table, available, '' if available == rows else ' (all its keys allow, of {} asked)'.format(rows)))
                    for plan in plans:
                        print('  {:<28} {:<12} {}'.format(plan.column, plan.source, plan.description))
                    for row in range(min(3, available)):
                        print('  sample: {}'.format(dict(zip(columns, makeRow(row)))))
                    continue
                inserted = synthesizeTable(database, table, rows, seed=arguments.seed, foreignKeys=foreignKeys, rules=rules)
            except SynthesisError as error:
                raise UsageError(str(error)) from error
            log.logging.info('{}: inserted {} synthetic row(s)'.format(table, inserted), extra={'table': table, 'rowCount': inserted})
            print('{}: inserted {} row(s)'.format(table, inserted))

    if arguments.dry_run:
        print('Parents are listed first. Foreign-key samples above come from the parents as they are now; '
              'a real run fills each parent before its children.')

    return EXIT_SUCCESS


def _commandClear(arguments: argparse.Namespace, log: Log) -> int:
    """Empties the target tables of the selected jobs, children first.

    Refuses incremental jobs: their stored watermark would survive, so the
    next run would reload only new rows into an empty table.
    """

    from ..generate.schema import SchemaError, clearOrder, clearTables

    jobsFile, databaseConfiguration = _loadDataJobs(arguments)
    jobs = {name: job for name, job in _selectJobs(jobsFile.jobs, arguments.job, log).items() if job.active}

    incremental = sorted(name for name, job in jobs.items() if job.watermarkColumn)
    if incremental:
        raise UsageError('refusing to clear the targets of incremental job(s) {}: their stored watermark would make the next run '
                         'load only new rows. Leave them out with --job'.format(', '.join(incremental)))

    tablesByDatabase: Dict[str, List[str]] = {}
    for job in jobs.values():
        tables = tablesByDatabase.setdefault(job.targetDatabase, [])
        if job.targetTableFinal.upper() not in {table.upper() for table in tables}:
            tables.append(job.targetTableFinal)

    if not arguments.dry_run and not arguments.yes:
        raise UsageError('clear deletes every row of {} table(s); pass --yes to do it, or --dry-run to see the plan'.format(
            sum(len(tables) for tables in tablesByDatabase.values())))

    for alias, tables in sorted(tablesByDatabase.items()):
        with Database(connectionSettings=databaseConfiguration[alias]) as database:
            # Checked before the plan is printed, or it lists tables that
            # aren't there and the run it describes fails.
            missing = [table for table in tables if not database.tableExists(table)]
            if missing:
                raise UsageError('{}: {} is not in the target, so there is nothing to empty. Create it with bauta schema, '
                                 'or leave its job out with --job'.format(alias, ', '.join(missing)))
            try:
                if arguments.dry_run:
                    print('{}: would empty, in order: {}'.format(alias, ', '.join(clearOrder(tables, database.getForeignKeys()))))
                    continue
                cleared = clearTables(database, tables)
            except SchemaError as error:
                raise UsageError('{}: {}'.format(alias, error)) from error
            except Exception as error:
                log.logging.error('{}: nothing was cleared -- {}'.format(alias, describeError(error)))
                return EXIT_JOBS_DID_NOT_SUCCEED

        for table, rows in cleared:
            log.logging.info('{}: emptied {} ({} row(s))'.format(alias, table, rows))
        print('{}: emptied {}'.format(alias, ', '.join(table for table, _ in cleared)))

    if not arguments.dry_run:
        # Emptied targets hold nothing masked under the old key any more, so
        # a key change is no longer a reason to refuse these jobs.
        memory, _ = _memoryBackend(arguments, jobsFile, databaseConfiguration)
        with memory:
            for name, job in jobs.items():
                if job.masking is not None:
                    memory.recordKeyFingerprint(name, None)
        print('Run the jobs with --force, so a `refresh` window cannot leave a cleared table empty.')

    return EXIT_SUCCESS
