"""The commands that build from a live schema: discover, subset, schema,
synthesize and clear.
"""
from __future__ import annotations

import argparse
import datetime
import sys
from typing import Dict, List, Optional, Sequence, Tuple

from ..configuration import isLake
from ..database import Database
from ..database.dialects import catalogTable, quoteIdentifier, quoteTableName
from ..log import Log
from ..log.scrubbing import describeError
from .common import (EXIT_JOBS_DID_NOT_SUCCEED, EXIT_SUCCESS, UsageError, _discoveryRules, _loadConnections, _loadDataJobs, _memoryBackend,
                     _readJobs, _requireDatabase, _resolveConfigurationPaths, _selectJobs, _writeOutput)


def _generatedHeading(command: str, source: str, target: str) -> List[str]:

    return [
        'Generated by `bauta {}` on {} from {}, loading into {}.'.format(command, datetime.date.today().isoformat(), source, target),
        '',
        'A proposal, not a policy. Review every column before running this -- the',
        'comment on each says what the suggestion was based on -- and set',
        'MASKING_KEY in the environment. Sampled values were read only to classify',
        'columns; none of them appear in this file.',
        '',
        ]


def _nextSteps(source: str, target: str, tables: Sequence[str], related: bool = False, allTables: Optional[str] = None) -> List[str]:
    """How to create the tables the generated jobs load, and how to refresh
    them. `allTables`, when every table was asked for, is the arguments that
    say so again, rather than one --table per table.
    """

    tableArguments = allTables if allTables is not None else ' '.join('--table {}'.format(table) for table in tables)
    if source == target:
        return [
            'Masking in place loads through <table>_masked_stage. Create the stage tables with:',
            '  bauta schema --connection {0} --target {0} {1} --stage-suffix _masked_stage --apply'.format(source, tableArguments),
            '',
            ]

    return [
        'Create any target tables that do not exist yet with:',
        '  bauta schema --connection {} --target {} {}{} --apply'.format(source, target, tableArguments, ' --related' if related else ''),
        'To refresh the copy later, empty it first, then run every job:',
        '  bauta clear --config <this directory> --yes && bauta run --config <this directory> --force',
        '',
        ]


def _requireTableSelection(arguments: argparse.Namespace) -> None:
    """Either the tables are named, or every one of them is asked for."""

    if arguments.all_tables and arguments.table:
        raise UsageError('--all-tables and --table name two different sets of tables; give one or the other')
    if not arguments.all_tables and not arguments.table:
        raise UsageError('name the tables with --table, repeated, or take every one with --all-tables')


def _commandDiscover(arguments: argparse.Namespace, log: Log) -> int:
    """Proposes a masking policy for each table from its schema and a sample,
    writing nothing to any database.
    """

    from ..generate.discovery import JobDraft, proposeTable, renderJobs

    if arguments.update:
        return _discoverUpdate(arguments, log)
    if arguments.apply or arguments.job:
        raise UsageError('--apply and --job go with --update')
    if not arguments.connection:
        raise UsageError('name the database to read with --connection, or pass --update to check the jobs file against its sources')

    _requireTableSelection(arguments)
    connectionConfiguration = _loadConnections(arguments)
    rules = _discoveryRules(arguments)
    target = arguments.target or arguments.connection
    _requireDatabase(connectionConfiguration, arguments.connection)
    targetSettings = _requireDatabase(connectionConfiguration, target)

    drafts = []
    with Database(connectionSettings=connectionConfiguration[arguments.connection]) as database:
        # Named as the catalog holds them, so a table written in quotes -- the
        # only way to name a reserved word -- matches its own foreign keys, and
        # gives a job and a key domain the same name a bare one would.
        requestedTables = database.listTables(schema=arguments.schema) if arguments.all_tables else arguments.table
        if not requestedTables:
            raise UsageError('{} holds no tables{}'.format(
                arguments.connection, ' in schema {}'.format(arguments.schema) if arguments.schema else ''))
        # The keys of the schema the tables are in, which --schema or a
        # qualified --table names, not only the connection's own.
        try:
            foreignKeys = database.getForeignKeys(arguments.schema) if arguments.all_tables else database.getForeignKeysFor(requestedTables)
        except NotImplementedError:
            foreignKeys = []
        tables = [catalogTable(database.type, table) for table in requestedTables]
        requested = {table.upper(): table for table in tables}
        for table in tables:
            log.logging.info('Sampling up to {} row(s) of {}'.format(arguments.sample, table))
            proposal = proposeTable(database, table, sampleSize=arguments.sample, foreignKeys=foreignKeys, rules=rules,
                                    maskKeys=arguments.mask_keys)
            # Parents first, so a target that enforces foreign keys accepts the load.
            parents = sorted({requested[foreignKey.referencedTable.upper()] for foreignKey in foreignKeys
                              if foreignKey.table.upper() == table.upper() and foreignKey.referencedTable.upper() in requested
                              and foreignKey.referencedTable.upper() != table.upper()})
            drafts.append(JobDraft(table=table, sourceQuery='SELECT * FROM {}'.format(database.statementName(table)),
                                   predecessors=parents, proposal=proposal))

    allTables = None
    if arguments.all_tables:
        allTables = '--all-tables' + (' --schema {}'.format(arguments.schema) if arguments.schema else '')
    heading = _generatedHeading('discover', arguments.connection, target) + _nextSteps(arguments.connection, target, requestedTables,
                                                                                       allTables=allTables)
    _writeOutput(renderJobs(drafts, arguments.connection, target, heading, keyVariable=arguments.key_variable,
                            chunkSize=arguments.chunk_size, targetType=targetSettings.type,
                            selfContained=arguments.self_contained), arguments.output)

    return EXIT_SUCCESS


def _discoverUpdate(arguments: argparse.Namespace, log: Log) -> int:
    """Each masked job in the jobs file against what its sourceQuery returns
    now: the columns it doesn't cover, proposed as discover would, and the
    ones it names that are gone. Exits 1 when any job has drifted and the
    change wasn't applied, so it can gate a pipeline as coverage does.
    """

    from ..generate.drift import DriftError, _wholeTable, applyDrift, findDrift, renderDrift

    for flag, given in (('--connection', arguments.connection), ('--table', arguments.table), ('--all-tables', arguments.all_tables),
                        ('--target', arguments.target), ('--output', arguments.output)):
        if given:
            raise UsageError('{} names what to discover afresh; --update reads the jobs file instead'.format(flag))

    jobsFile, connectionConfiguration = _loadDataJobs(arguments)
    jobsPath, _ = _resolveConfigurationPaths(arguments)
    document = _readJobs(jobsPath)
    rules = _discoveryRules(arguments)
    jobs = {name: job for name, job in _selectJobs(jobsFile.jobs, arguments.job, log).items()
            if job.masking is not None and not isLake(connectionConfiguration.get(job.sourceConnection))}

    drifts = []
    for alias in sorted({job.sourceConnection for job in jobs.values()}):
        _requireDatabase(connectionConfiguration, alias)
        with Database(connectionSettings=connectionConfiguration[alias]) as database:
            # The keys of each schema a job reads whole, where a new key
            # column finds the domain its reference shares.
            wholeTables = [table for table in (_wholeTable(job.sourceQuery) for job in jobs.values() if job.sourceConnection == alias) if table]
            try:
                foreignKeys = database.getForeignKeysFor(wholeTables)
            except NotImplementedError:
                foreignKeys = []
            for name in sorted(name for name, job in jobs.items() if job.sourceConnection == alias):
                drift = findDrift(database, name, jobs[name], rules=rules, sampleSize=arguments.sample, maskKeys=arguments.mask_keys,
                                  foreignKeys=foreignKeys)
                if drift.any():
                    drifts.append(drift)

    if not drifts:
        print('{} masked job(s) checked: every policy names exactly the columns its sourceQuery returns'.format(len(jobs)))
        return EXIT_SUCCESS

    sys.stdout.write(renderDrift(drifts, document.origins))
    if not arguments.apply:
        print('{} of {} masked job(s) have drifted. Review the proposals above, then apply them with --apply'.format(len(drifts), len(jobs)))
        return EXIT_JOBS_DID_NOT_SUCCEED

    # One file at a time, every edit to it made before it is written, so a
    # failure part-way leaves each file as it was or wholly updated.
    failed = []
    for path in dict.fromkeys(document.origins[drift.job] for drift in drifts):
        text = path.read_text()
        try:
            for drift in drifts:
                if document.origins[drift.job] == path:
                    text = applyDrift(text, drift)
        except DriftError as error:
            failed.append('{}: {}'.format(path, error))
            continue
        path.write_text(text)
        log.logging.info('Updated {}'.format(path))

    if failed:
        raise UsageError('could not apply every proposal; nothing was written to these files:\n' + '\n'.join(failed))

    print('Applied to {} job(s). Review the lines marked "proposed by discover --update" before the next run'.format(len(drifts)))
    return EXIT_SUCCESS


def _commandSubset(arguments: argparse.Namespace, log: Log) -> int:
    """Generates one data job per table for a referentially complete subset,
    loading parents before children, with masking proposals if --mask is set
    or the target requires masking.
    """

    from ..generate.discovery import JobDraft, proposeTable, renderJobs
    from ..generate.subset import SubsetError, planSubset

    connectionConfiguration = _loadConnections(arguments)
    rules = _discoveryRules(arguments)
    _requireDatabase(connectionConfiguration, arguments.connection)
    targetSettings = _requireDatabase(connectionConfiguration, arguments.target)

    if arguments.target == arguments.connection:
        raise UsageError('--target must differ from --connection: a subset is loaded into another database, not over its source')

    # A target that requires masking refuses every job without a policy, so
    # jobs generated without one could only fail validation.
    mask = arguments.mask or targetSettings.requireMasking
    if mask and not arguments.mask:
        log.logging.info('{} requires masking, so each table gets a proposed policy, as with --mask'.format(arguments.target))
    elif not mask:
        log.logging.warning('These jobs copy every column as it is in {}. --mask proposes a masking policy for each table, as discover does; '
                            'without it, add one to each job before running them'.format(arguments.connection))

    with Database(connectionSettings=connectionConfiguration[arguments.connection]) as database:
        # The root's schema's keys: a subset follows references within it.
        foreignKeys = database.getForeignKeysFor([arguments.root])

        try:
            plan = planSubset(foreignKeys, root=arguments.root, where=arguments.where, followChildren=not arguments.no_children,
                              ignore=arguments.ignore_foreign_key or [], materialize=database.dialect.supportsMaterializedSelections(),
                              quote=lambda name: quoteIdentifier(database.type, name),
                              quoteTable=lambda name: quoteTableName(database.type, name))
        except SubsetError as error:
            raise UsageError(str(error)) from error

        log.logging.info('Subset covers {} table(s): {}'.format(len(plan.tables), ', '.join(plan.tables)))
        for foreignKey in plan.ignored:
            log.logging.warning('Ignoring foreign key {}.{} -> {}; rows may reference ones outside the subset'.format(
                foreignKey.table, ','.join(foreignKey.columns), foreignKey.referencedTable))

        drafts = []
        for table in plan.tables:
            proposal = proposeTable(database, table, sampleSize=arguments.sample, foreignKeys=foreignKeys, rules=rules,
                                    maskKeys=arguments.mask_keys) if mask else None
            drafts.append(JobDraft(table=table, sourceQuery=plan.queries[table], predecessors=plan.parents[table], proposal=proposal))

    heading = _generatedHeading('subset', arguments.connection, arguments.target) + [
        'Rooted at {} where {}.'.format(arguments.root, arguments.where),
        'Jobs load parents before children, so the target can keep its foreign keys.',
        '',
        ] + _nextSteps(arguments.connection, arguments.target, [arguments.root], related=True)
    _writeOutput(renderJobs(drafts, arguments.connection, arguments.target, heading, keyVariable=arguments.key_variable,
                            chunkSize=arguments.chunk_size, targetType=targetSettings.type,
                            selfContained=arguments.self_contained), arguments.output)

    return EXIT_SUCCESS


def _commandSchema(arguments: argparse.Namespace, log: Log) -> int:
    """Generates CREATE TABLE statements for the target, or applies them.

    --apply skips tables the target already has, so it's safe to re-run, and
    never alters or drops anything.
    """

    from ..generate.schema import SchemaError, createStatements, readTable, renderScript
    from ..generate.subset import relatedTables

    _requireTableSelection(arguments)
    if arguments.all_tables and arguments.related:
        raise UsageError('--related adds the tables related to --table; --all-tables already takes every table')
    connectionConfiguration = _loadConnections(arguments)
    sourceSettings = _requireDatabase(connectionConfiguration, arguments.connection)
    targetSettings = _requireDatabase(connectionConfiguration, arguments.target)
    stagesOnly = arguments.connection == arguments.target

    if stagesOnly and not arguments.stage_suffix:
        raise UsageError('--target is the source database, so its tables already exist; pass --stage-suffix to create stage tables for them')

    with Database(connectionSettings=sourceSettings) as source:
        foreignKeys = source.getForeignKeys(arguments.schema) if arguments.all_tables else source.getForeignKeysFor(arguments.table)
        if arguments.all_tables:
            tables = [catalogTable(source.type, table) for table in source.listTables(schema=arguments.schema)]
            if not tables:
                raise UsageError('{} holds no tables{}'.format(
                    arguments.connection, ' in schema {}'.format(arguments.schema) if arguments.schema else ''))
        elif arguments.related:
            tables = relatedTables(foreignKeys, arguments.table, followChildren=not arguments.no_children)
        else:
            tables = arguments.table
        try:
            definitions = [readTable(source, table, foreignKeys) for table in tables]
            statements = createStatements(sourceSettings.type, targetSettings.type, definitions, includeForeignKeys=not arguments.no_foreign_keys,
                                          stageSuffix=arguments.stage_suffix, stagesOnly=stagesOnly)
        except SchemaError as error:
            raise UsageError(str(error)) from error

    if not arguments.apply:
        heading = [
            'Generated by `bauta schema` on {} from {} ({}), for {} ({}).'.format(
                datetime.date.today().isoformat(), arguments.connection, sourceSettings.type.value, arguments.target, targetSettings.type.value),
            'Columns, nullability, primary keys and foreign keys only: no indexes, defaults or constraints beyond those.',
            'Review the commented type choices before applying.',
            ]
        _writeOutput(renderScript(statements, heading), arguments.output)
        return EXIT_SUCCESS

    created = skipped = 0
    with Database(connectionSettings=targetSettings, create=True) as target:
        for statement in statements:
            if target.tableExists(statement.table):
                log.logging.info('{}: already exists, left as it is'.format(statement.table))
                skipped += 1
                continue
            for note in statement.notes:
                log.logging.warning('{}: {}'.format(statement.table, note))
            try:
                target.alter(statement.sql)
            except Exception as error:
                raise UsageError('could not create {} ({} created before it): {}'.format(
                    statement.table, created, describeError(error))) from error
            log.logging.info('{}: created'.format(statement.table))
            created += 1

    print('schema applied to {}: {} table(s) created, {} already existed'.format(arguments.target, created, skipped))

    return EXIT_SUCCESS


def _parseTableRows(entries: Sequence[str], default: int) -> List[Tuple[str, int]]:
    """`--table orders:500` entries, with `--rows` for any without a count."""

    parsed = []
    for entry in entries:
        table, separator, count = entry.rpartition(':')
        if not separator:
            parsed.append((entry, default))
            continue
        if not table or not count.isdigit() or int(count) < 1:
            raise UsageError('--table takes TABLE or TABLE:ROWS with a positive count, got {!r}'.format(entry))
        parsed.append((table, int(count)))

    return parsed


def _commandSynthesize(arguments: argparse.Namespace, log: Log) -> int:
    """Fills existing tables with generated rows, parents first.

    Writes only with --yes, like `clear`. --dry-run shows what each column
    would get and a few generated rows, which are safe to print.
    """

    from ..generate.schema import SchemaError, orderParentsFirst
    from ..generate.synthesize import SynthesisError, planTable, synthesizeTable

    connectionConfiguration = _loadConnections(arguments)
    rules = _discoveryRules(arguments)
    _requireDatabase(connectionConfiguration, arguments.connection)
    requested = dict(_parseTableRows(arguments.table, arguments.rows))

    if not arguments.dry_run and not arguments.yes:
        raise UsageError('synthesize inserts generated rows into {}; pass --yes to do it, or --dry-run to see the plan'.format(
            ', '.join(requested)))

    with Database(connectionSettings=connectionConfiguration[arguments.connection]) as database:
        foreignKeys = database.getForeignKeysFor(list(requested))
        try:
            order = orderParentsFirst(requested, foreignKeys)
        except SchemaError as error:
            raise UsageError(str(error)) from error

        for table in order:
            rows = requested[table]
            try:
                if arguments.dry_run:
                    columns, makeRow, plans, available = planTable(database, table, rows, seed=arguments.seed, foreignKeys=foreignKeys, rules=rules)
                    print('{}: {} row(s){}'.format(table, available, '' if available == rows else ' (all its keys allow, of {} asked)'.format(rows)))
                    for plan in plans:
                        print('  {:<28} {:<12} {}'.format(plan.column, plan.source, plan.description))
                    for row in range(min(3, available)):
                        print('  sample: {}'.format(dict(zip(columns, makeRow(row)))))
                    continue
                inserted = synthesizeTable(database, table, rows, seed=arguments.seed, foreignKeys=foreignKeys, rules=rules)
            except SynthesisError as error:
                raise UsageError(str(error)) from error
            log.logging.info('{}: inserted {} synthetic row(s)'.format(table, inserted), extra={'table': table, 'rowCount': inserted})
            print('{}: inserted {} row(s)'.format(table, inserted))

    if arguments.dry_run:
        print('Parents are listed first. Foreign-key samples above come from the parents as they are now; '
              'a real run fills each parent before its children.')

    return EXIT_SUCCESS


def _commandClear(arguments: argparse.Namespace, log: Log) -> int:
    """Empties the target tables of the selected jobs, children first.

    Refuses incremental jobs: their stored watermark would survive, so the
    next run would reload only new rows into an empty table.
    """

    from ..generate.schema import SchemaError, clearOrder, clearTables

    jobsFile, connectionConfiguration = _loadDataJobs(arguments)
    jobs = {name: job for name, job in _selectJobs(jobsFile.jobs, arguments.job, log).items() if job.active}

    incremental = sorted(name for name, job in jobs.items() if job.watermarkColumn)
    if incremental:
        raise UsageError('refusing to clear the targets of incremental job(s) {}: their stored watermark would make the next run '
                         'load only new rows. Leave them out with --job'.format(', '.join(incremental)))

    writingLakes = sorted(name for name, job in jobs.items() if isLake(connectionConfiguration.get(job.targetConnection)))
    if writingLakes:
        raise UsageError('clear empties tables in databases, and job(s) {} write files or Iceberg tables. Leave them out with '
                         '--job'.format(', '.join(writingLakes)))

    tablesByDatabase: Dict[str, List[str]] = {}
    for job in jobs.values():
        tables = tablesByDatabase.setdefault(job.targetConnection, [])
        if job.targetTableFinal.upper() not in {table.upper() for table in tables}:
            tables.append(job.targetTableFinal)

    if not arguments.dry_run and not arguments.yes:
        raise UsageError('clear deletes every row of {} table(s); pass --yes to do it, or --dry-run to see the plan'.format(
            sum(len(tables) for tables in tablesByDatabase.values())))

    for alias, tables in sorted(tablesByDatabase.items()):
        with Database(connectionSettings=connectionConfiguration[alias]) as database:
            # Checked before the plan is printed, or it lists tables that
            # aren't there and the run it describes fails.
            missing = [table for table in tables if not database.tableExists(table)]
            if missing:
                raise UsageError('{}: {} is not in the target, so there is nothing to empty. Create it with bauta schema, '
                                 'or leave its job out with --job'.format(alias, ', '.join(missing)))
            try:
                if arguments.dry_run:
                    print('{}: would empty, in order: {}'.format(alias, ', '.join(clearOrder(tables, database.getForeignKeysFor(tables)))))
                    continue
                cleared = clearTables(database, tables)
            except SchemaError as error:
                raise UsageError('{}: {}'.format(alias, error)) from error
            except Exception as error:
                log.logging.error('{}: nothing was cleared -- {}'.format(alias, describeError(error)))
                return EXIT_JOBS_DID_NOT_SUCCEED

        for table, rows in cleared:
            log.logging.info('{}: emptied {} ({} row(s))'.format(alias, table, rows))
        print('{}: emptied {}'.format(alias, ', '.join(table for table, _ in cleared)))

    if not arguments.dry_run:
        # Emptied targets hold nothing masked under the old key any more, so
        # a key change is no longer a reason to refuse these jobs.
        memory, _ = _memoryBackend(arguments, jobsFile, connectionConfiguration)
        with memory:
            for name, job in jobs.items():
                if job.masking is not None:
                    memory.recordKeyFingerprint(name, None)
        print('Run the jobs with --force, so a `refresh` window cannot leave a cleared table empty.')

    return EXIT_SUCCESS
